version: '3.8'
services:
  postgres:
    image: postgres:13  # You can change the version if necessary
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: myuser  # Replace with your desired user
      POSTGRES_PASSWORD: mypassword  # Replace with your desired password
      POSTGRES_DB: myflixdb  # Replace with your desired database name
    ports:
      - "5432:5432"  # Exposing PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage volume for the database
volumes:
  postgres_data:
